auto: true

markdown: rdiscount
pygments: true
paginate: 10
permalink: pretty

title: Yong's Blog
url: http://yongluo2013.github.io
feed: /atom.xml
author_info: <a href="http://yongluo2013.github.io/">Yong Luo</a>