auto: true

markdown: rdiscount
pygments: true
paginate: 10
permalink: pretty

title: Kong's Blog
url: http://lingxiankong.github.io
feed: /atom.xml
author_info: <a href="http://lingxiankong.github.io/">Lingxian Kong</a>