auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Luo Yong
url: http://yongluo2013.github.io
feed: /atom.xml
author_info: <a href="http://yongluo2013.github.io/">Luo Yong</a>
